version: "3.8"
services:
  db:
    container_name: db
    image: mysql:5.7
    command: --init-file /data/db/db.sql --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: prueba
    volumes:
      - ./db/db.sql:/data/db/db.sql
    ports:
      - "9906:3306"
    networks:
      - app-network

  app:
    build: .
    container_name: web-app
    working_dir: /var/www
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: prueba
      DB_NAME: sds
    volumes:
      - ./:/var/www
    links:
      - db:db
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 3000:80
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
